
trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
# Step 1: Checkout the code from GitHub repository
- checkout: self
  displayName: 'Checkout Code from GitHub'

# Step 2: Install dependencies (if any)
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    packageType: 'sdk'
    version: '6.x.x' # Specify the version of .NET Core SDK

# Step 3: Build the function app (if needed)
- task: DotNetCoreCLI@2
  displayName: 'Build Function App'
  inputs:
    command: 'build'
    projects: '**/*.csproj' # Path to your .csproj file

# Step 4: Deploy the function app to Azure
- task: AzureFunctionApp@1
  displayName: 'Deploy Function App to Azure'
  inputs:
    azureSubscription: '<your-service-connection>' # Replace with your Azure service connection name
    appType: 'functionApp'
    appName: '<your-function-app-name>' # Replace with your Function App name
    package: '$(System.DefaultWorkingDirectory)/**/*.zip' # Path to the package to be deployed
